-- ----------------------------
-- Table structure for `weapons`
-- ----------------------------
DROP TABLE IF EXISTS `weapons`;
CREATE TABLE `weapons` (
  `id` int(10) unsigned NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `unidentified_name_id` varchar(255) NOT NULL,
  `identified_name_id` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `is_twohanded` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `material` varchar(255) NOT NULL,
  `weight` int(10) unsigned NOT NULL DEFAULT '0',
  `inv_gfx_id` int(10) unsigned NOT NULL,
  `grd_gfx_id` int(10) unsigned NOT NULL,
  `item_desc_id` int(10) unsigned NOT NULL DEFAULT '0',
  `dmg_small` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `dmg_large` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `range` tinyint(3) NOT NULL DEFAULT '0',
  `safe_enchant` tinyint(3) NOT NULL DEFAULT '0',
  `use_royal` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `use_knight` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `use_wizard` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `use_elf` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `use_darkelf` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `use_dragonknight` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `use_illusionist` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `hit_modifier` tinyint(3) NOT NULL DEFAULT '0',
  `dmg_modifier` tinyint(3) NOT NULL DEFAULT '0',
  `str` tinyint(3) NOT NULL DEFAULT '0',
  `con` tinyint(3) NOT NULL DEFAULT '0',
  `dex` tinyint(3) NOT NULL DEFAULT '0',
  `int` tinyint(3) NOT NULL DEFAULT '0',
  `wis` tinyint(3) NOT NULL DEFAULT '0',
  `cha` tinyint(3) NOT NULL DEFAULT '0',
  `hp` int(10) NOT NULL DEFAULT '0',
  `mp` int(10) NOT NULL DEFAULT '0',
  `hpr` int(10) NOT NULL DEFAULT '0',
  `mpr` int(10) NOT NULL DEFAULT '0',
  `sp` tinyint(3) NOT NULL DEFAULT '0',
  `mr` tinyint(3) NOT NULL DEFAULT '0',
  `is_haste` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `double_dmg_chance` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `weakness_exposure` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `magic_dmg_modifier` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `can_be_dmg` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `min_level` int(3) unsigned NOT NULL DEFAULT '0',
  `max_level` int(3) unsigned NOT NULL DEFAULT '0',
  `bless` int(1) unsigned NOT NULL DEFAULT '0',
  `tradable` int(1) unsigned NOT NULL DEFAULT '1',
  `deletable` int(1) unsigned NOT NULL DEFAULT '1',
  `charge_time` int(10) unsigned NOT NULL DEFAULT '0',
  `expiration_time` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
