ALTER TABLE `accounts` MODIFY COLUMN `name` varchar(255) NOT NULL;
ALTER TABLE `accounts` MODIFY COLUMN `password` varchar(255) NOT NULL;
ALTER TABLE `accounts` MODIFY COLUMN `ip` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `accounts` MODIFY COLUMN `character_slot` tinyint(3) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `armor_sets` MODIFY COLUMN `id` int(10) unsigned NOT NULL;
ALTER TABLE `armor_sets` MODIFY COLUMN `note` varchar(255) DEFAULT NULL;
ALTER TABLE `armor_sets` MODIFY COLUMN `potion_recovery_rate` tinyint(3) NOT NULL DEFAULT '0';
ALTER TABLE `armors` MODIFY COLUMN `name` varchar(255) DEFAULT NULL;
ALTER TABLE `armors` MODIFY COLUMN `unidentified_name_id` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `armors` MODIFY COLUMN `identified_name_id` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `armors` MODIFY COLUMN `type` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `armors` MODIFY COLUMN `material` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `armors` MODIFY COLUMN `expiration_time` varchar(255) DEFAULT NULL;
ALTER TABLE `armors` MODIFY COLUMN `potion_recovery_rate` tinyint(3) NOT NULL DEFAULT '0';
ALTER TABLE `ban_ips` MODIFY COLUMN `ip` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `beginner_items` MODIFY COLUMN `id` int(10) unsigned NOT NULL;
ALTER TABLE `beginner_items` MODIFY COLUMN `note` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `board` MODIFY COLUMN `name` varchar(255) DEFAULT NULL;
ALTER TABLE `board` MODIFY COLUMN `date` varchar(255) DEFAULT NULL;
ALTER TABLE `board` MODIFY COLUMN `title` varchar(255) DEFAULT NULL;
ALTER TABLE `castles` MODIFY COLUMN `name` varchar(255) DEFAULT NULL;
ALTER TABLE `character_bookmarks` MODIFY COLUMN `name` varchar(255) DEFAULT NULL;
ALTER TABLE `character_buddys` MODIFY COLUMN `buddy_name` varchar(255) DEFAULT NULL;
ALTER TABLE `character_skills` MODIFY COLUMN `skill_name` varchar(255) DEFAULT NULL;
ALTER TABLE `characters` MODIFY COLUMN `name` varchar(255) DEFAULT NULL;
ALTER TABLE `characters` MODIFY COLUMN `title` varchar(255) DEFAULT NULL DEFAULT '';
ALTER TABLE `characters` MODIFY COLUMN `clan_name` varchar(255) DEFAULT NULL DEFAULT '';
ALTER TABLE `clans` MODIFY COLUMN `clan_name` varchar(255) DEFAULT NULL DEFAULT '';
ALTER TABLE `clans` MODIFY COLUMN `leader_name` varchar(255) DEFAULT NULL DEFAULT '';
ALTER TABLE `cooking_ingredients` MODIFY COLUMN `id` int(10) unsigned NOT NULL;
ALTER TABLE `drop_rates` MODIFY COLUMN `item_id` int(10) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `drop_rates` MODIFY COLUMN `note` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `dungeon_random` MODIFY COLUMN `note` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `dungeons` MODIFY COLUMN `note` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `etc_items` MODIFY COLUMN `name` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `etc_items` MODIFY COLUMN `unidentified_name_id` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `etc_items` MODIFY COLUMN `identified_name_id` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `etc_items` MODIFY COLUMN `item_type` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `etc_items` MODIFY COLUMN `use_type` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `etc_items` MODIFY COLUMN `material` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `etc_items` MODIFY COLUMN `expiration_time` varchar(255) DEFAULT NULL;
ALTER TABLE `house_auction` MODIFY COLUMN `house_name` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `house_auction` MODIFY COLUMN `location` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `house_auction` MODIFY COLUMN `old_owner` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `house_auction` MODIFY COLUMN `bidder` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `houses` MODIFY COLUMN `house_name` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `houses` MODIFY COLUMN `location` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `inns` MODIFY COLUMN `name` varchar(255) DEFAULT '';
ALTER TABLE `inventory_items` MODIFY COLUMN `id` int(10) unsigned NOT NULL;
ALTER TABLE `inventory_items` MODIFY COLUMN `owner_id` int(10) unsigned NOT NULL;
ALTER TABLE `inventory_items` MODIFY COLUMN `location` int(10) NOT NULL;
ALTER TABLE `inventory_items` MODIFY COLUMN `item_id` int(10) unsigned NOT NULL;
ALTER TABLE `inventory_items` MODIFY COLUMN `item_count` int(10) unsigned NOT NULL;
ALTER TABLE `inventory_items` MODIFY COLUMN `durability` int(10) NOT NULL;
ALTER TABLE `inventory_items` MODIFY COLUMN `charge_count` int(10) unsigned NOT NULL;
ALTER TABLE `inventory_items` MODIFY COLUMN `charge_time` int(10) unsigned NOT NULL;
ALTER TABLE `inventory_items` MODIFY COLUMN `hp` int(10) NOT NULL DEFAULT '0';
ALTER TABLE `inventory_items` MODIFY COLUMN `hpr` int(10) NOT NULL DEFAULT '0';
ALTER TABLE `inventory_items` MODIFY COLUMN `mp` int(10) NOT NULL DEFAULT '0';
ALTER TABLE `inventory_items` MODIFY COLUMN `mpr` int(10) NOT NULL DEFAULT '0';
ALTER TABLE `inventory_items` MODIFY COLUMN `potion_recovery_rate` tinyint(3) NOT NULL DEFAULT '0';
ALTER TABLE `letters` MODIFY COLUMN `sender` varchar(255) DEFAULT NULL;
ALTER TABLE `letters` MODIFY COLUMN `receiver` varchar(255) DEFAULT NULL;
ALTER TABLE `letters` MODIFY COLUMN `date` varchar(255) DEFAULT NULL;
ALTER TABLE `log_accelerator` MODIFY COLUMN `account_name` varchar(255) NOT NULL;
ALTER TABLE `log_accelerator` MODIFY COLUMN `name` varchar(255) NOT NULL;
ALTER TABLE `log_accelerator` MODIFY COLUMN `clan_name` varchar(255) DEFAULT NULL;
ALTER TABLE `log_chat` MODIFY COLUMN `account_name` varchar(255) NOT NULL;
ALTER TABLE `log_chat` MODIFY COLUMN `name` varchar(255) NOT NULL;
ALTER TABLE `log_chat` MODIFY COLUMN `clan_name` varchar(255) DEFAULT NULL;
ALTER TABLE `log_chat` MODIFY COLUMN `target_account_name` varchar(255) DEFAULT NULL;
ALTER TABLE `log_chat` MODIFY COLUMN `target_name` varchar(255) DEFAULT NULL;
ALTER TABLE `log_chat` MODIFY COLUMN `target_clan_name` varchar(255) DEFAULT NULL;
ALTER TABLE `log_chat` MODIFY COLUMN `content` varchar(255) NOT NULL;
ALTER TABLE `magic_dolls` MODIFY COLUMN `note` varchar(255) DEFAULT '';
ALTER TABLE `mails` MODIFY COLUMN `sender` varchar(255) DEFAULT NULL;
ALTER TABLE `mails` MODIFY COLUMN `receiver` varchar(255) DEFAULT NULL;
ALTER TABLE `mails` MODIFY COLUMN `date` varchar(255) DEFAULT NULL;
ALTER TABLE `map_ids` MODIFY COLUMN `location_name` varchar(255) DEFAULT NULL;
ALTER TABLE `mob_groups` MODIFY COLUMN `id` int(10) unsigned NOT NULL;
ALTER TABLE `mob_skills` MODIFY COLUMN `mob_name` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `npc` MODIFY COLUMN `name` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `npc` MODIFY COLUMN `name_id` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `npc` MODIFY COLUMN `note` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `npc` MODIFY COLUMN `impl` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `npc` MODIFY COLUMN `family` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `npc` MODIFY COLUMN `agro_family` tinyint(1) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `npc` MODIFY COLUMN `hpr_interval` int(10) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `npc` MODIFY COLUMN `hpr` int(10) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `npc` MODIFY COLUMN `mpr_interval` int(10) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `npc` MODIFY COLUMN `mpr` int(10) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `npc` MODIFY COLUMN `random_level` tinyint(3) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `npc` MODIFY COLUMN `random_hp` int(10) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `npc` MODIFY COLUMN `random_mp` int(10) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `npc` MODIFY COLUMN `random_ac` tinyint(3) NOT NULL DEFAULT '0';
ALTER TABLE `npc` MODIFY COLUMN `random_exp` int(10) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `npc` MODIFY COLUMN `random_lawful` int(10) NOT NULL DEFAULT '0';
ALTER TABLE `npc` MODIFY COLUMN `damage_reduction` int(10) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `npc` MODIFY COLUMN `bow_act_id` int(10) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `npc` MODIFY COLUMN `change_head` tinyint(1) NOT NULL DEFAULT '0';
ALTER TABLE `npc_actions` MODIFY COLUMN `normal_action` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `npc_actions` MODIFY COLUMN `chaotic_action` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `npc_actions` MODIFY COLUMN `teleport_url` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `npc_actions` MODIFY COLUMN `teleport_urla` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `npc_chats` MODIFY COLUMN `note` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `npc_chats` MODIFY COLUMN `chat_id1` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `npc_chats` MODIFY COLUMN `chat_id2` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `npc_chats` MODIFY COLUMN `chat_id3` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `npc_chats` MODIFY COLUMN `chat_id4` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `npc_chats` MODIFY COLUMN `chat_id5` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `pet_items` MODIFY COLUMN `note` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `pet_items` MODIFY COLUMN `hit_modifier` tinyint(3) NOT NULL DEFAULT '0';
ALTER TABLE `pet_items` MODIFY COLUMN `dmg_modifier` tinyint(3) NOT NULL DEFAULT '0';
ALTER TABLE `pet_items` MODIFY COLUMN `ac` tinyint(3) NOT NULL DEFAULT '0';
ALTER TABLE `pet_items` MODIFY COLUMN `str` tinyint(3) NOT NULL DEFAULT '0';
ALTER TABLE `pet_items` MODIFY COLUMN `con` tinyint(3) NOT NULL DEFAULT '0';
ALTER TABLE `pet_items` MODIFY COLUMN `dex` tinyint(3) NOT NULL DEFAULT '0';
ALTER TABLE `pet_items` MODIFY COLUMN `int` tinyint(3) NOT NULL DEFAULT '0';
ALTER TABLE `pet_items` MODIFY COLUMN `wis` tinyint(3) NOT NULL DEFAULT '0';
ALTER TABLE `pet_items` MODIFY COLUMN `mr` tinyint(3) NOT NULL DEFAULT '0';
ALTER TABLE `pet_items` MODIFY COLUMN `use_type` tinyint(3) NOT NULL DEFAULT '0';
ALTER TABLE `pet_types` MODIFY COLUMN `name` varchar(255) NOT NULL;
ALTER TABLE `pets` MODIFY COLUMN `name` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `pets` MODIFY COLUMN `food` tinyint(3) NOT NULL DEFAULT '0';
ALTER TABLE `race_tickets` MODIFY COLUMN `item_obj_id` int(10) NOT NULL;
ALTER TABLE `race_tickets` MODIFY COLUMN `round` int(10) NOT NULL;
ALTER TABLE `race_tickets` MODIFY COLUMN `victory` tinyint(1) NOT NULL;
ALTER TABLE `race_tickets` MODIFY COLUMN `runner_num` tinyint(3) NOT NULL;
ALTER TABLE `resolvents` MODIFY COLUMN `note` varchar(255) NOT NULL;
ALTER TABLE `restart_locations` MODIFY COLUMN `note` varchar(255) NOT NULL;
ALTER TABLE `return_locations` MODIFY COLUMN `note` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `skills` MODIFY COLUMN `skill_id` int(10) unsigned NOT NULL;
ALTER TABLE `skills` MODIFY COLUMN `name` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `skills` MODIFY COLUMN `target` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `skills` MODIFY COLUMN `name_id` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `spawn_boss` MODIFY COLUMN `id` int(10) unsigned NOT NULL;
ALTER TABLE `spawn_boss` MODIFY COLUMN `location` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `spawn_boss` MODIFY COLUMN `cycle_type` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `spawn_doors` MODIFY COLUMN `location` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `spawn_lights` MODIFY COLUMN `id` int(10) unsigned NOT NULL;
ALTER TABLE `spawn_mobs` MODIFY COLUMN `id` int(10) unsigned NOT NULL;
ALTER TABLE `spawn_mobs` MODIFY COLUMN `location` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `spawn_npc` MODIFY COLUMN `id` int(10) unsigned NOT NULL;
ALTER TABLE `spawn_npc` MODIFY COLUMN `location` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `spawn_traps` MODIFY COLUMN `note` varchar(255) DEFAULT NULL;
ALTER TABLE `spawn_ub` MODIFY COLUMN `location` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `towns` MODIFY COLUMN `name` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `towns` MODIFY COLUMN `leader_name` varchar(255) DEFAULT NULL;
ALTER TABLE `traps` MODIFY COLUMN `note` varchar(255) DEFAULT NULL;
ALTER TABLE `traps` MODIFY COLUMN `type` varchar(255) NOT NULL;
ALTER TABLE `ub_settings` MODIFY COLUMN `ub_name` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `weapon_skills` MODIFY COLUMN `weapon_id` int(10) unsigned NOT NULL;
ALTER TABLE `weapons` MODIFY COLUMN `name` varchar(255) DEFAULT NULL;
ALTER TABLE `weapons` MODIFY COLUMN `unidentified_name_id` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `weapons` MODIFY COLUMN `identified_name_id` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `weapons` MODIFY COLUMN `type` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `weapons` MODIFY COLUMN `material` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `weapons` MODIFY COLUMN `expiration_time` varchar(255) DEFAULT NULL;
